version: '3.4'

services:
  blazorapp:
    image: ${DOCKER_REGISTRY-}blazorapp
    build:
      context: .
      dockerfile: BlazorApp/Dockerfile
    links:
      - "app.redis"

  app.seq: 
    image: datalust/seq:latest
    container_name: app-seq
    environment:
        - ACCEPT_EULA=Y
    ports: 
        - 5341:5341
        - 8081:80

  app.redis:
    image: redis:6.2-alpine
    container_name: app-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local